### ISSUE TITLE
How to Load glb from stream?

### ISSUE THREAD

**Issue by CeSun** [vpenades/SharpGLTF#178]
I use the SharpGLTF library in Android. The glb file is stored in the asstes directory of the apk. It needs to use the android API to open the stream, so the following code cannot work:
```csharp
var model = SharpGLTF.Schema2.ModelRoot.Load("model.gltf");

```
I need an api for parsing glb files from a stream, does SharpGLTF support it?

The expected code is as follows:

```csharp
var stream = Asstes.Open("abc.glb");   // android api
var model = SharpGLTF.Schema2.ModelRoot.LoadFromStream(stream);

```

**Comment by vpenades** [comment]
```c#
var model = SharpGLTF.Schema2.ModelRoot.ReadGLB(stream);
```

**Comment by CeSun** [comment]
> ```cs
> var model = SharpGLTF.Schema2.ModelRoot.ReadGLB(stream);
> ```

It will throw exception:
```
System.NotSupportedException: 'Specified method is not supported.'
  at Android.Runtime.InputStreamInvoker.get_Length() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/InputStreamInvoker.cs:line 137
   at SharpGLTF.Schema2._BinarySerialization._ReadBinaryHeader(BinaryReader binaryReader)
   at SharpGLTF.Schema2._BinarySerialization.ReadBinaryFile(Stream stream)
   at SharpGLTF.Schema2.ReadContext._ReadGLB(Stream stream)
   at SharpGLTF.Schema2.ReadContext.ReadBinarySchema2(Stream stream)
   at SharpGLTF.Schema2.ModelRoot.ReadGLB(Stream stream, ReadSettings settings)
```

**Comment by vpenades** [comment]
I guess you're opening a stream from a network?  the opened stream needs to be seekable, so it must be opened from a file or from memory.

**Comment by vpenades** [comment]
the library needs to know the length of the stream; it's weird that being a local asset, the stream fails to give that information...
