### ISSUE TITLE
SharpGLTF.Validation.LinkException: Extensions: KHR_draco_mesh_compressionModel ?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [vpenades/SharpGLTF#180]
The asset is valid.  

[new.zip](https://github.com/vpenades/SharpGLTF/files/11338991/new.zip)

**Reading glb with draco compression**
```
var model = SharpGLTF.Schema2.ModelRoot.Load("new.glb");
var str = model.GetJsonPreview();
Console.WriteLine(str);
```
got error
```
Unhandled exception. SharpGLTF.Validation.LinkException: Extensions: KHR_draco_mesh_compressionModel generated by <> seems to be malformed; Please, check the file at https://github.khronos.org/glTF-Validator/
   at SharpGLTF.Schema2.ReadContext._FilterErrors(ValueTuple`2 mv)
   at SharpGLTF.Schema2.ReadContext.ReadBinarySchema2(Stream stream)
   at SharpGLTF.Schema2.ReadContext.ReadSchema2(Stream stream)
   at SharpGLTF.Schema2.ReadContext.ReadSchema2(String resourceName)
   at SharpGLTF.Schema2.ModelRoot.Load(String filePath, ReadSettings settings)
   at Program.<Main>$(String[] args) in D:\glb_run\Program.cs:line 2
```

**To Reproduce**
code above  

**please complete the following information:**
 - OS: windows10
 - SharpGLTF.Core Version [1.0.0-alpha0028]

**Comment by vpenades** [comment]
#44
