### ISSUE TITLE
[BUG] when merging meshes with buffers exceeding the maximum capacity

### ISSUE THREAD

**Issue by KisliPlug** [vpenades/SharpGLTF#196]
Hello! I try convert big model from Navisworks (i think it's not important) 
I can do it with part of this model, but when i try export whole model i got this error.

[ERR] System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at SharpGLTF.Geometry.PackedBuffer.MergeBuffers()
   at SharpGLTF.Geometry.PackedPrimitiveBuilder`1.MergeBuffers(IEnumerable`1 primitives)
   at SharpGLTF.Schema2.Toolkit.CreateMeshes[TMaterial](ModelRoot root, Converter`2 materialConverter, SceneBuilderSchema2Settings settings, IMeshBuilder`1[] meshBuilders)
   at SharpGLTF.Scenes.Schema2SceneBuilder.AddGeometryResources(ModelRoot root, IEnumerable`1 srcScenes, SceneBuilderSchema2Settings settings)
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2(IEnumerable`1 srcScenes, SceneBuilderSchema2Settings settings)
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2(SceneBuilderSchema2Settings settings)
   at MeshToBim.Navis.Logic.MeshExporter.<Export>d__6.MoveNext()

**Comment by KisliPlug** [comment]
Hello! Thanks for clarification! I disabled buffer merge, but it this problem not gone. I think it happen in this place

https://github.com/vpenades/SharpGLTF/blob/master/src/SharpGLTF.Toolkit/Schema2/MeshExtensions.cs on 87 line.

In this place buffer always merged, and settings not checked. 
I'm not sure if it part of algorithm or can be skiped.

**Comment by vpenades** [comment]
I'll look into it

**Comment by vpenades** [comment]
I've uploaded some changes that fix the line you mentioned, could you try the code from the repository and tell me if it successfully loads the model?

**Comment by KisliPlug** [comment]
Hello! Thank you very match! I will check it today, and let you know about results!

**Comment by KisliPlug** [comment]
I thing now it's works in huge modes. thanks!

**Comment by vpenades** [comment]
> Or for glb we always must merge buffers?

Yes, this is a requirement of the GLB format, because GLBs only support one buffer.

See:
- https://github.com/KhronosGroup/glTF/issues/1318
- https://github.com/KhronosGroup/glTF/issues/2114

so if you're trying to save a very big model, your only choice left is to save it to glTF.

**Comment by KisliPlug** [comment]
Thanks for clarification! I's very sad 😢

**Comment by vpenades** [comment]
Indeed. My feeling is that the khronos board thought that GLB is to create relatively, self contained small packages, and whoever needs very large models should use glTF format, possibly compressed inside a ZIP file.
